
        
 version: 2.1

 workflows:
   my-workflow:
     jobs:
       - run-tests

                     


      
 jobs:
   run-tests:
     docker:
      - image: circleci/ruby:2.5.5-stretch-node-browsers
     steps:
       - checkout 
       - run: echo "hello world"
       
#    second_job:
#      docker:
#        - image: cimg/base:2020.01
#      steps:
#        - run: echo "bye world. This is a scheduled workflow/job"
#       #test
